### ISSUE TITLE
Data Seeding and Updating pipline

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1810]
- [ ] Data preparation of static tables in parquet
- [ ] Buildings to parquet
- [ ] AOI to parquet
- [ ] POI to parquet
- [ ] Grid to parquet?
- [ ] Population to parquet
- [ ] POI preparation refactor
- [ ] Population disaggregation refactor
- [ ] Data seeding (add new study area) --> This needs to be split further
- [ ] Data seeding patch existing study area --> This needs to be split further
- [ ] Documentation and flowchart + public table schema
- [ ] Handle existing tables that might not be needed anymore due to parquet
- [ ] Refactor scenarios to work with parquet+db-changesets
- [ ] Define baseline/structure CLI for data preparation
- [ ] Build baseline CLI
