### ISSUE TITLE
1. User Dashboard/ Design

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/goat#1836]
[Interface Architecture](https://plan4better-my.sharepoint.com/:x:/g/personal/ana_sasso_plan4better_de/EZx3n6tdXN9GlYTWieywGs8BpZ9gi5hJlHMt-hmX-HuDjg?e=mMVhG8&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0)
<img width="900" alt="Screenshot 2023-04-24 at 21 23 56" src="https://user-images.githubusercontent.com/116002158/234143885-b7920f57-1014-4f07-ae04-32abfe9f9254.png">
--------------------------------------------------------------------------------
**Main Dashboard Flows**

- [x] Onboarding | _New client, account setup_
- [ ] Subscribe GOAT Plan | _Plans display, checkout_
- [ ] Unsubscribe | _Cancel Plan subscription_
- [ ] Delete Account |  
- [ ] Reset password |  
- [ ] Edit project permissions | _Project preview, user access to project_
- [x] Manage user permissions | _CRUD user in a organisation_
- [x] Create New Project |  
- [x] Upload Data |  
- [x] #2281

**Comment by AnaSasso** [comment]
User dashboard should follow the same Visual ID as Plan4Better website?

**Comment by AnaSasso** [comment]
- [ ] Review Architecture Interface
- [ ] Review Flows
- [ ] Prioritise Flows
