### ISSUE TITLE
Add buffer as option next to the isochrones

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2137]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2138
- [ ] https://github.com/goat-community/goat/issues/2141
- [ ] https://github.com/goat-community/goat/issues/2139
- [ ] https://github.com/goat-community/goat/issues/2140
- [ ] https://github.com/goat-community/goat/issues/2142
```

**Comment by EPajares** [comment]
The aim is to extend the current isochrone calculation mode by a new calculation type which is a simple buffer of varying size. It should also work to adjust the size with the slider. The user should define the buffer size e.g. 1000 m and define the interval e.g. 100 m
