### ISSUE TITLE
Add car routing

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2144]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/data_preparation/issues/204
- [ ] https://github.com/goat-community/goat/issues/2135
- [ ] https://github.com/goat-community/goat/issues/2369
```
