### ISSUE TITLE
Refactor Heatmap

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2146]
```[tasklist]
### Tasks
- [ ] #1796
- [ ] https://github.com/goat-community/goat/issues/2016
- [ ] https://github.com/goat-community/goat/issues/2076
- [ ] https://github.com/goat-community/goat/issues/2077
- [ ] https://github.com/goat-community/goat/issues/2078
- [ ] https://github.com/goat-community/goat/issues/2087
- [ ] https://github.com/goat-community/goat/issues/2086
- [ ] https://github.com/goat-community/goat/issues/1911
- [ ] https://github.com/goat-community/goat/issues/2082
- [ ] https://github.com/goat-community/goat/issues/2208
```
