### ISSUE TITLE
Data Preparation and Migration

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2147]
```[tasklist]
### Tasks
- [ ] #2148
- [ ] https://github.com/goat-community/goat/issues/2209
- [ ] https://github.com/goat-community/goat/issues/2083
- [ ] https://github.com/goat-community/goat/issues/2210
- [ ] https://github.com/goat-community/goat/issues/2211
- [ ] https://github.com/goat-community/goat/issues/2287
```
