### ISSUE TITLE
Authorization - GOAT v2

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2165]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2166
- [ ] https://github.com/goat-community/goat/issues/2167
- [ ] https://github.com/goat-community/goat/issues/2168
- [ ] https://github.com/goat-community/goat/issues/2169
- [ ] https://github.com/goat-community/goat/issues/2170
- [ ] https://github.com/goat-community/goat/issues/2212
- [ ] https://github.com/goat-community/goat/issues/2213
- [ ] https://github.com/goat-community/goat/issues/2268
- [ ] https://github.com/goat-community/goat/issues/2271
- [ ] https://github.com/goat-community/goat/issues/2269
- [ ] https://github.com/goat-community/goat/issues/2274
- [ ] https://github.com/goat-community/goat/issues/2276
- [ ] https://github.com/goat-community/goat/issues/2270
- [ ] https://github.com/goat-community/goat/issues/2275
- [ ] https://github.com/goat-community/goat/issues/2320
- [ ] https://github.com/goat-community/goat/issues/2321
- [ ] https://github.com/goat-community/goat/issues/2322
- [ ] https://github.com/goat-community/goat/issues/2409
- [ ] https://github.com/goat-community/goat/issues/2410
- [ ] https://github.com/goat-community/goat/issues/2411
- [ ] https://github.com/goat-community/goat/issues/2257
- [ ] https://github.com/goat-community/goat/issues/2536
- [ ] https://github.com/goat-community/goat/issues/2617
- [ ] https://github.com/goat-community/goat/issues/2681
- [ ] https://github.com/goat-community/goat/issues/2682
- [ ] https://github.com/goat-community/goat/issues/2683
- [ ] https://github.com/goat-community/goat/issues/2684
- [ ] https://github.com/goat-community/goat/issues/2983
- [ ] https://github.com/goat-community/goat/issues/3154
```
