### ISSUE TITLE
User Dashboard - GOAT V2

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2175]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2176
- [ ] https://github.com/goat-community/goat/issues/2177
- [ ] https://github.com/goat-community/goat/issues/2178
- [ ] https://github.com/goat-community/goat/issues/2179
- [ ] https://github.com/goat-community/goat/issues/2180
- [ ] https://github.com/goat-community/goat/issues/2181
- [ ] https://github.com/goat-community/goat/issues/2182
- [ ] https://github.com/goat-community/goat/issues/2266
- [ ] https://github.com/goat-community/goat/issues/2288
- [ ] https://github.com/goat-community/goat/issues/2289
- [ ] https://github.com/goat-community/goat/issues/2290
- [ ] https://github.com/goat-community/goat/issues/2377
- [ ] https://github.com/goat-community/goat/issues/2380
- [ ] https://github.com/goat-community/goat/issues/2381
- [ ] https://github.com/goat-community/goat/issues/2382
- [ ] https://github.com/goat-community/goat/issues/2413
- [ ] https://github.com/goat-community/goat/issues/2412
- [ ] https://github.com/goat-community/goat/issues/2488
- [ ] https://github.com/goat-community/goat/issues/2491
- [ ] https://github.com/goat-community/goat/issues/2522
- [ ] https://github.com/goat-community/goat/issues/2538
- [ ] https://github.com/goat-community/goat/issues/2539
- [ ] https://github.com/goat-community/goat/issues/2540
- [ ] https://github.com/goat-community/goat/issues/2602
- [ ] https://github.com/goat-community/goat/issues/2603
- [ ] https://github.com/goat-community/goat/issues/2649
- [ ] https://github.com/goat-community/goat/issues/2650
- [ ] https://github.com/goat-community/goat/issues/2652
- [ ] https://github.com/goat-community/goat/issues/2651
- [ ] https://github.com/goat-community/goat/issues/2653
- [ ] https://github.com/goat-community/goat/issues/2654
- [ ] https://github.com/goat-community/goat/issues/2927
```

**Comment by majkshkurti** [comment]
@AnaSasso

**Comment by AnaSasso** [comment]
Interface Architecture  https://github.com/goat-community/goat/issues/1836
![image](https://user-images.githubusercontent.com/116002158/234242531-564cd8e7-ea9d-4da9-b0c8-6290ce4c9863.png)

**Comment by AnaSasso** [comment]
Hey guys, so this https://github.com/goat-community/goat/issues/2181 is on [figma](https://www.figma.com/file/tu6pPILBRSUuy3Hbu8Lphk/Goat-3.0?type=design&node-id=11768%3A127162&t=AsIoHirBbMnWzXrj-1)
enjoy 💫
