### ISSUE TITLE
GOAT v2 Atomic components

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2214]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2235
- [ ] https://github.com/goat-community/goat/issues/2236
- [ ] https://github.com/goat-community/goat/issues/2244
- [ ] https://github.com/goat-community/goat/issues/2238
- [ ] https://github.com/goat-community/goat/issues/2237
- [ ] https://github.com/goat-community/goat/issues/2239
- [ ] https://github.com/goat-community/goat/issues/2242
- [ ] https://github.com/goat-community/goat/issues/2240
- [ ] https://github.com/goat-community/goat/issues/2243
- [ ] https://github.com/goat-community/goat/issues/2241
- [ ] https://github.com/goat-community/goat/issues/2245
- [ ] https://github.com/goat-community/goat/issues/2251
```

**Comment by EPajares** [comment]
Check which components we need and then start on the most basic ones first.

**Comment by EPajares** [comment]
@cinaaaa @Ebubeker @majkshkurti we can here rather assign the individual issues to people. We can check in the daily
