### ISSUE TITLE
Setting and Content GOAT v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2319]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2323
- [ ] https://github.com/goat-community/goat/issues/2324
- [ ] https://github.com/goat-community/goat/issues/2325
- [ ] https://github.com/goat-community/goat/issues/2326
- [ ] https://github.com/goat-community/goat/issues/2327
- [ ] https://github.com/goat-community/goat/issues/2370
- [ ] https://github.com/goat-community/goat/issues/2373
- [ ] https://github.com/goat-community/goat/issues/2478
- [ ] https://github.com/goat-community/goat/issues/2513
- [ ] https://github.com/goat-community/goat/issues/2533
- [ ] https://github.com/goat-community/goat/issues/2534
- [ ] https://github.com/goat-community/goat/issues/2535
- [ ] https://github.com/goat-community/goat/issues/2655
- [ ] https://github.com/goat-community/goat/issues/2656
- [ ] https://github.com/goat-community/goat/issues/2657
- [ ] https://github.com/goat-community/goat/issues/2658
- [ ] https://github.com/goat-community/goat/issues/2659
- [ ] https://github.com/goat-community/goat/issues/2660
- [ ] https://github.com/goat-community/goat/issues/2685
- [ ] https://github.com/goat-community/goat/issues/2686
- [ ] https://github.com/goat-community/goat/issues/2687
- [ ] https://github.com/goat-community/goat/issues/2693
- [ ] https://github.com/goat-community/goat/issues/2694
- [ ] https://github.com/goat-community/goat/issues/2700
- [ ] https://github.com/goat-community/goat/issues/2715
- [ ] https://github.com/goat-community/goat/issues/2716
- [ ] https://github.com/goat-community/goat/issues/2718
- [ ] https://github.com/goat-community/goat/issues/2719
- [ ] https://github.com/goat-community/goat/issues/2745
- [ ] https://github.com/goat-community/goat/issues/2747
- [ ] https://github.com/goat-community/goat/issues/2749
- [ ] https://github.com/goat-community/goat/issues/2763
- [ ] https://github.com/goat-community/goat/issues/2827
- [ ] https://github.com/goat-community/goat/issues/2828
- [ ] https://github.com/goat-community/goat/issues/2846
- [ ] https://github.com/goat-community/goat/issues/2849
- [ ] https://github.com/goat-community/goat/issues/2857
- [ ] https://github.com/goat-community/goat/issues/2856
- [ ] https://github.com/goat-community/goat/issues/2874
- [ ] https://github.com/goat-community/goat/issues/2958
- [ ] https://github.com/goat-community/goat/issues/2957
- [ ] https://github.com/goat-community/goat/issues/2960
- [ ] https://github.com/goat-community/goat/issues/3020
- [ ] https://github.com/goat-community/goat/issues/3214
- [ ] https://github.com/goat-community/goat/issues/3225
```
