### ISSUE TITLE
Map - GOAT v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2362]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2383
- [ ] https://github.com/goat-community/goat/issues/2363
- [ ] https://github.com/goat-community/goat/issues/2364
- [ ] https://github.com/goat-community/goat/issues/2365
- [ ] https://github.com/goat-community/goat/issues/2366
- [ ] https://github.com/goat-community/goat/issues/2415
- [ ] https://github.com/goat-community/goat/issues/2416
- [ ] https://github.com/goat-community/goat/issues/2417
- [ ] https://github.com/goat-community/goat/issues/2418
- [ ] https://github.com/goat-community/goat/issues/2490
- [ ] https://github.com/goat-community/goat/issues/2505
- [ ] https://github.com/goat-community/goat/issues/2521
- [ ] https://github.com/goat-community/goat/issues/2549
- [ ] https://github.com/goat-community/goat/issues/2550
- [ ] https://github.com/goat-community/goat/issues/2551
- [ ] https://github.com/goat-community/goat/issues/2552
- [ ] https://github.com/goat-community/goat/issues/2554
- [ ] https://github.com/goat-community/goat/issues/2667
- [ ] https://github.com/goat-community/goat/issues/2754
- [ ] https://github.com/goat-community/goat/issues/2873
- [ ] https://github.com/goat-community/goat/issues/2928
- [ ] https://github.com/goat-community/goat/issues/2930
- [ ] https://github.com/goat-community/goat/issues/2945
- [ ] https://github.com/goat-community/goat/issues/2992
- [ ] https://github.com/goat-community/goat/issues/2993
- [ ] https://github.com/goat-community/goat/issues/3234
```
