### ISSUE TITLE
Clean GOAT repo v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2371]
```[tasklist]
### Tasks
- [ ] Remove authentication and authorization from GOAT
- [ ] Remove legacy crud and endpoints
- [ ] Delete old client
```

**Comment by EPajares** [comment]
Basically, the repo is outdated, and we moved to a service architecture with separate repos. So this can be closed.
