### ISSUE TITLE
GOAT CI/CD v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2374]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2378
- [ ] https://github.com/goat-community/goat/issues/2379
- [ ] https://github.com/goat-community/goat/issues/2423
- [ ] https://github.com/goat-community/goat/issues/2425
- [ ] https://github.com/goat-community/goat/issues/2528
- [ ] https://github.com/goat-community/goat/issues/2761
- [ ] https://github.com/goat-community/goat/issues/2762
- [ ] https://github.com/goat-community/goat/issues/2765
- [ ] https://github.com/goat-community/goat/issues/2847
- [ ] https://github.com/goat-community/goat/issues/2981
- [ ] https://github.com/goat-community/goat/issues/2982
- [ ] https://github.com/goat-community/goat/issues/3068
```
