### ISSUE TITLE
GOAT Analysis v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2414]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2399
- [ ] https://github.com/goat-community/goat/issues/2421
- [ ] https://github.com/goat-community/goat/issues/2422
- [ ] https://github.com/goat-community/goat/issues/2420
- [ ] https://github.com/goat-community/goat/issues/2502
- [ ] https://github.com/goat-community/goat/issues/2503
- [ ] https://github.com/goat-community/goat/issues/2523
- [ ] https://github.com/goat-community/goat/issues/1923
- [ ] https://github.com/goat-community/goat/issues/2524
- [ ] https://github.com/goat-community/goat/issues/2558
- [ ] https://github.com/goat-community/goat/issues/2606
- [ ] https://github.com/goat-community/goat/issues/2607
- [ ] https://github.com/goat-community/goat/issues/2627
- [ ] https://github.com/goat-community/goat/issues/2637
- [ ] https://github.com/goat-community/goat/issues/2639
- [ ] https://github.com/goat-community/goat/issues/2691
- [ ] https://github.com/goat-community/goat/issues/2692
- [ ] https://github.com/goat-community/goat/issues/2709
- [ ] https://github.com/goat-community/goat/issues/2714
- [ ] https://github.com/goat-community/goat/issues/2722
- [ ] https://github.com/goat-community/goat/issues/2725
- [ ] https://github.com/goat-community/goat/issues/2727
- [ ] https://github.com/goat-community/goat/issues/2728
- [ ] https://github.com/goat-community/goat/issues/2729
- [ ] https://github.com/goat-community/goat/issues/2766
- [ ] https://github.com/goat-community/goat/issues/2810
- [ ] https://github.com/goat-community/goat/issues/2824
- [ ] https://github.com/goat-community/goat/issues/2825
- [ ] https://github.com/goat-community/goat/issues/2826
- [ ] https://github.com/goat-community/goat/issues/2832
- [ ] https://github.com/goat-community/goat/issues/2833
- [ ] https://github.com/goat-community/goat/issues/2739
- [ ] https://github.com/goat-community/goat/issues/2735
- [ ] https://github.com/goat-community/goat/issues/2805
- [ ] https://github.com/goat-community/goat/issues/2836
- [ ] https://github.com/goat-community/goat/issues/2837
- [ ] https://github.com/goat-community/goat/issues/2838
- [ ] https://github.com/goat-community/goat/issues/2839
- [ ] https://github.com/goat-community/goat/issues/2840
- [ ] https://github.com/goat-community/goat/issues/2841
- [ ] https://github.com/goat-community/goat/issues/2842
- [ ] https://github.com/goat-community/goat/issues/2843
- [ ] https://github.com/goat-community/goat/issues/2844
- [ ] https://github.com/goat-community/goat/issues/2921
- [ ] https://github.com/goat-community/goat/issues/2922
- [ ] https://github.com/goat-community/goat/issues/2932
- [ ] https://github.com/goat-community/goat/issues/2961
- [ ] https://github.com/goat-community/goat/issues/2963
- [ ] https://github.com/goat-community/goat/issues/3003
- [ ] https://github.com/goat-community/goat/issues/3086
- [ ] https://github.com/goat-community/goat/issues/3087
- [ ] https://github.com/goat-community/goat/issues/3148
- [ ] https://github.com/goat-community/goat/issues/3156
- [ ] https://github.com/goat-community/goat/issues/3218
- [ ] https://github.com/goat-community/goat/issues/3232
- [ ] https://github.com/goat-community/goat/issues/3250
- [ ] https://github.com/goat-community/goat/issues/3254
- [ ] https://github.com/goat-community/goat/issues/3255
```
