### ISSUE TITLE
Test table partitioning for different use cases

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2422]
```[tasklist]
### Tasks
- [x] Check database dumps
- [ ] Check tipg
- [x] Check reading, updating and deleting
- [x] Check query performance and parallelization
- [x] Check database functions
```
