### ISSUE TITLE
Other smaller issues

### ISSUE THREAD

**Issue by Ebubeker** [goat-community/goat#2442]
Smaller issues that I have to fix in the dashboard:

```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2445
- [ ] https://github.com/goat-community/goat/issues/2446
- [ ] https://github.com/goat-community/goat/issues/2447
- [ ] https://github.com/goat-community/goat/issues/2448
- [ ] https://github.com/goat-community/goat/issues/2449
- [ ] https://github.com/goat-community/goat/issues/2450
- [ ] https://github.com/goat-community/goat/issues/2451
- [ ] https://github.com/goat-community/goat/issues/2452
- [ ] https://github.com/goat-community/goat/issues/2456
- [ ] https://github.com/goat-community/goat/issues/2457
- [ ] https://github.com/goat-community/goat/issues/2458
- [ ] https://github.com/goat-community/goat/issues/2459
- [ ] https://github.com/goat-community/goat/issues/2466
- [ ] https://github.com/goat-community/goat/issues/2613
- [ ] https://github.com/goat-community/goat/issues/2614
- [ ] https://github.com/goat-community/goat/issues/2615
```
