### ISSUE TITLE
Implement layer styling

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2505]
**User needs**
Our users (GIS novices and planners) would like to have the opportunity to style geospatial data on the map. This data can his own data or data that is produced using GOAT like indicators (e.g. isochrones or heatmaps). With the styling the user can customize the look and feel of the layer, but the styling is also the basis for users to understand complex data. 

**Acceptance criteria**
- Users can style point, line and polygon layers.
- User can change the fill and stroke color of the symbol. 
- User can change the stroke pattern of the symbol.
- For points users should also be able to pick different SVG-Icons as symbols, which can be changed in their color. 
- Users can apply a simple style (one symbology for all features of the layer) or attribute-based styling in which one an attribute of the layer is user to define the style (attributes are used to build groups. Each group receives a symbol). 
- Attribute based styling needs to be differentiated if the attribute is a text or the attribute is a number. For text we can only apply "categories"

**Example for categorized:**

![Image](https://github.com/goat-community/goat/assets/42171996/95b74662-0e57-4397-8b5f-3fc16a3d76b8)

- For attribute-based styling we can apply both categories and what is also often called "graduated". of a the users should be able to user Quintile, Equal breaks and Manual breaks as classification to build the groups.
- The map should dynamically change when the user changes the style. The style should be autosaved to the layer of the project.

**Notes**
We need to define the styling library to be used. There is a library called Geostyler that we are using at the moment (https://geostyler.github.io/geostyler-demo/) this can be translated into mapbox. Another option is saving mapbox styles directly. The advantage of Geostyler is that the structure feels more understandable and it can be translated into different other formats.

**Figma**
https://www.figma.com/file/tu6pPILBRSUuy3Hbu8Lphk/Goat-3.0?type=design&node-id=12778-147141&mode=design&t=hOL3KvRqMIBQ29L4-0
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2575
- [ ] https://github.com/goat-community/goat/issues/2576
- [ ] https://github.com/goat-community/goat/issues/2577
- [ ] https://github.com/goat-community/goat/issues/2578
- [ ] https://github.com/goat-community/goat/issues/2579
- [ ] https://github.com/goat-community/goat/issues/2581
- [x] https://github.com/goat-community/goat/issues/2609
- [ ] https://github.com/goat-community/goat/issues/2610
- [ ] https://github.com/goat-community/goat/issues/2611
```

**Comment by EPajares** [comment]
For now we thing the best idea is to implement the styling standard used by maplibre:
https://maplibre.org/maplibre-style-spec/
