### ISSUE TITLE
Scenario v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2515]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2914
- [ ] https://github.com/goat-community/goat/issues/2916
- [ ] https://github.com/goat-community/goat/issues/2915
- [ ] https://github.com/goat-community/goat/issues/2917
- [ ] https://github.com/goat-community/goat/issues/2918
- [ ] https://github.com/goat-community/goat/issues/2919
- [ ] https://github.com/goat-community/goat/issues/3048
- [ ] https://github.com/goat-community/goat/issues/3049
- [ ] https://github.com/goat-community/goat/issues/3258
- [ ] https://github.com/goat-community/goat/issues/3259
```
