### ISSUE TITLE
Charts v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2516]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2573
- [ ] https://github.com/goat-community/goat/issues/2764
- [ ] https://github.com/goat-community/goat/issues/2909
- [ ] https://github.com/goat-community/goat/issues/2910
- [ ] https://github.com/goat-community/goat/issues/2912
- [ ] https://github.com/goat-community/goat/issues/2952
- [ ] https://github.com/goat-community/goat/issues/2953
- [ ] https://github.com/goat-community/goat/issues/2954
- [ ] https://github.com/goat-community/goat/issues/2955
- [ ] https://github.com/goat-community/goat/issues/3008
- [ ] https://github.com/goat-community/goat/issues/3010
- [ ] https://github.com/goat-community/goat/issues/3216
```
