### ISSUE TITLE
Filter layer v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2520]
**User needs**
Our users (GIS novices and planners) would like to filter layer based on the attributes to use them in a second step for visualization (styling) or for the analyses. 

**Acceptance criteria**
- Allow the user to filter by one or more columns using classical filter operation (is, between) etc.
- It should be dynamically differentiated between numbers and strings. Number can have more filters as we can operator such as <, >, between etc. For texts we can just have "is" and "in" for now. One example is category is 'tram_stop' or category in ('tram_stop', 'bus_stop').
- The relevance of a specific category in the dropdown to pick the attribute should be shown by the feature count of the respective field. e.g. tram_stop (count = 20) 
- For numerical comparisons it would be great if we can load the distribution of values as sort of "histogram"
![Image](https://github.com/goat-community/goat/assets/42171996/bc34d1d5-4b88-4b73-ad9c-463aaa75f8b6)
(from Kepler)
- The performance should not be to bad on this as users would expect the field to show fast.

**Notes**
This is the current status in Figma: 
https://www.figma.com/file/tu6pPILBRSUuy3Hbu8Lphk/Goat-3.0?type=design&node-id=13436-129115&mode=design&t=rwxyjna7FkigR9da-0

```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2471
- [ ] https://github.com/goat-community/goat/issues/2541
- [ ] https://github.com/goat-community/goat/issues/2542
- [ ] https://github.com/goat-community/goat/issues/2543
- [ ] https://github.com/goat-community/goat/issues/2545
- [ ] https://github.com/goat-community/goat/issues/2546
- [ ] https://github.com/goat-community/goat/issues/2547
- [ ] https://github.com/goat-community/goat/issues/2548
- [ ] https://github.com/goat-community/goat/issues/2604
- [ ] https://github.com/goat-community/goat/issues/2666
- [ ] https://github.com/goat-community/goat/issues/2848
```
