### ISSUE TITLE
R5 GTFS Workflow / Performance

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2607]
We are using R5 to compute traveltimes for public transport and the car. The main problem we are facing with our current solution is the poor performance. There are different reasons for this but from our current experience they are for us mostly the following:

- Our network is too large (we have whole Germany in one network bundle)
- R5 computes always isochrones up to 120 minutes. For our use cases though we are only using traveltimes up to 60 minutes. 
- R5 computes always five quantiles but we are only using one. 

We decided to test with subregional networks to have smaller networks and therefore better performance. We are having a postgresql table listing the regions with their geometries. Meanwhile it would be interesting exploring the Java code to see if we can do some optimizations. Overall, I suggest the following concrete tasks:

```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2619
- [ ] https://github.com/goat-community/goat/issues/2620
- [ ] https://github.com/goat-community/goat/issues/2621
- [ ] https://github.com/goat-community/goat/issues/2622
- [ ] https://github.com/goat-community/goat/issues/2623
- [ ] https://github.com/goat-community/goat/issues/2773
- [ ] https://github.com/goat-community/goat/issues/2774
- [ ] https://github.com/goat-community/goat/issues/2779
- [ ] https://github.com/goat-community/goat/issues/2854
- [ ] https://github.com/goat-community/goat/issues/2908
- [ ] https://github.com/goat-community/goat/issues/3000
```
