### ISSUE TITLE
GTFS DB data preparation

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2627]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2642
- [ ] https://github.com/goat-community/goat/issues/2643
- [ ] https://github.com/goat-community/goat/issues/2644
- [ ] https://github.com/goat-community/goat/issues/2645
- [ ] https://github.com/goat-community/goat/issues/2646
- [ ] https://github.com/goat-community/goat/issues/2674
```
