### ISSUE TITLE
Refactor GOAT Client

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2631]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2634
- [ ] https://github.com/goat-community/goat/issues/2632
- [ ] https://github.com/goat-community/goat/issues/2633
- [ ] https://github.com/goat-community/goat/issues/2635
- [ ] https://github.com/goat-community/goat/issues/2636
- [ ] https://github.com/goat-community/goat/issues/2641
```
