### ISSUE TITLE
Isochrone endpoint

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2637]
The endpoint for isochrones will be splitted in the new version. Active mobility will be separated from motorized mobility.
One core problem with active mobility isochrone is its performance for larger networks. This is mostly due to the long reading times of the routing network from database. Once we have the calculation time faster, we should increase the traveltime for walking/cycling to up to 30 minutes.

One avenue that was studied is loading the data for the base network in memory and patching it with scenario data on the fly. This mean the service should be optimized for memory and might rather a monolothic (or collection of monoliths) with more resources as our classical API Pods. Accordingly the Isochrone should receive its own service and be requested from the GOAT Core API similiar to the R5.

```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2703
- [ ] https://github.com/goat-community/goat/issues/2704
- [ ] https://github.com/goat-community/goat/issues/2640
- [ ] https://github.com/goat-community/goat/issues/2705
- [ ] https://github.com/goat-community/goat/issues/2706
- [ ] https://github.com/goat-community/goat/issues/2707
- [ ] https://github.com/goat-community/goat/issues/2708
- [ ] https://github.com/goat-community/goat/issues/2713
- [ ] https://github.com/goat-community/goat/issues/2717
- [ ] https://github.com/goat-community/goat/issues/2750
- [ ] https://github.com/goat-community/goat/issues/2751
- [ ] https://github.com/goat-community/goat/issues/2752
- [ ] https://github.com/goat-community/goat/issues/2759
- [ ] https://github.com/goat-community/goat/issues/2778
- [ ] https://github.com/goat-community/goat/issues/2808
- [ ] https://github.com/goat-community/goat/issues/2809
- [ ] https://github.com/goat-community/goat/issues/2835
```
