### ISSUE TITLE
Base data v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2668]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2645
- [ ] https://github.com/goat-community/goat/issues/2644
- [ ] https://github.com/goat-community/goat/issues/2627
- [ ] https://github.com/goat-community/goat/issues/2607
- [ ] https://github.com/goat-community/goat/issues/2317
- [ ] https://github.com/goat-community/goat/issues/2669
- [ ] https://github.com/goat-community/goat/issues/2673
- [ ] https://github.com/goat-community/goat/issues/2710
- [ ] https://github.com/goat-community/goat/issues/2711
- [ ] https://github.com/goat-community/data_preparation/issues/238
- [ ] https://github.com/goat-community/data_management/issues/413
- [ ] https://github.com/goat-community/data_management/issues/402
- [ ] https://github.com/goat-community/data_management/issues/404
- [ ] https://github.com/goat-community/data_preparation/issues/247
- [ ] https://github.com/goat-community/data_preparation/issues/246
- [ ] https://github.com/goat-community/data_management/issues/382
- [ ] https://github.com/goat-community/data_management/issues/410
- [ ] https://github.com/goat-community/goat/issues/2772
- [ ] https://github.com/goat-community/data_management/issues/392
- [ ] https://github.com/goat-community/goat/issues/2920
- [ ] https://github.com/goat-community/goat/issues/3021
- [ ] https://github.com/goat-community/goat/issues/3067
- [ ] https://github.com/goat-community/goat/issues/3071
- [ ] https://github.com/goat-community/goat/issues/3072
- [ ] https://github.com/goat-community/goat/issues/3073
- [ ] https://github.com/goat-community/goat/issues/3075
- [ ] https://github.com/goat-community/goat/issues/3076
- [ ] https://github.com/goat-community/goat/issues/3078
- [ ] https://github.com/goat-community/goat/issues/3079
- [ ] https://github.com/goat-community/goat/issues/3081
- [ ] https://github.com/goat-community/goat/issues/3083
- [ ] https://github.com/goat-community/goat/issues/3084
- [ ] https://github.com/goat-community/goat/issues/3236
```
