### ISSUE TITLE
Prepare Walking/Cycling network

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2669]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2670
- [ ] https://github.com/goat-community/goat/issues/2672
- [ ] https://github.com/goat-community/goat/issues/2671
- [ ] https://github.com/goat-community/goat/issues/2701
- [ ] https://github.com/goat-community/goat/issues/2702
- [ ] https://github.com/goat-community/goat/issues/2753
```
