### ISSUE TITLE
Prepare POIs

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2711]
```[tasklist]
### Tasks
- [ ] Finalize poi schmas and kart workflow
- [ ] Validate config data preparation
- [ ] Finish data subscription
```

**Comment by Philipp-Otter** [comment]
dublicated
