### ISSUE TITLE
Check for needed helper endpoints for indicators/toolbox

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2722]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2723
- [ ] https://github.com/goat-community/goat/issues/2724
- [ ] https://github.com/goat-community/goat/issues/2597
- [ ] https://github.com/goat-community/goat/issues/2541
```
