### ISSUE TITLE
Map tools

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2727]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2738
- [ ] https://github.com/goat-community/goat/issues/2739
- [ ] https://github.com/goat-community/goat/issues/2740
- [ ] https://github.com/goat-community/goat/issues/2741
- [ ] https://github.com/goat-community/goat/issues/2735
- [ ] https://github.com/goat-community/goat/issues/2733
- [ ] https://github.com/goat-community/goat/issues/2742
- [ ] https://github.com/goat-community/goat/issues/2743
- [ ] https://github.com/goat-community/goat/issues/2805
- [ ] https://github.com/goat-community/goat/issues/2806
```
