### ISSUE TITLE
Pending tasks: Overture network preparation

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2753]
```[tasklist]
### Tasks
- [ ] Process network islands
- [ ] Handle sub-segment property variance
- [x] Re-verify DEM tiles import (source data has potentially changed?)
- [x] Process wider Europe region data
- [ ] Handle no-data values in DEM raster more elegantly
- [ ] Handle directionality property of segments
- [ ] Handle segment flags
- [x] Use precise region geom filtering for optimal DEM tile selection
- [ ] Merge segment restrictions processing script / SQL function into data_preparation
- [ ] Create index on h3_6 column during overture_network preparation and use new code for computing segment impedance values
```
