### ISSUE TITLE
Heatmap endpoints

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2766]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2767
- [ ] https://github.com/goat-community/goat/issues/2768
- [ ] https://github.com/goat-community/goat/issues/2769
- [ ] https://github.com/goat-community/goat/issues/2770
- [ ] https://github.com/goat-community/goat/issues/2726
- [ ] https://github.com/goat-community/goat/issues/2829
- [ ] https://github.com/goat-community/goat/issues/2830
- [ ] https://github.com/goat-community/goat/issues/2934
- [ ] https://github.com/goat-community/goat/issues/3001
- [ ] https://github.com/goat-community/goat/issues/3249
```
