### ISSUE TITLE
GTFS: Future workflow, data clean-up tasks

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2772]
```[tasklist]
### Tasks (automated GTFS workflow)
- [x] Fetch latest Germany data from DELFI
- [ ] Fetch data for other European countries (sources to be identified)
- [x] Split PT study area into smaller sub-regions
- [x] Create buffered geom for sub-region
- [x] Filter GTFS dataset to only include data for a Tuesday, Saturday and Sunday
- [x] For each sub-region, create GTFS sub-dataset (use stop based geometric intersection with buffered geom)
- [x] Export and zip datasets
- [ ] Apply Nuremburg (and other) data fixes if required
- [ ] Reassign tram and rail routes from certain cities to route type 400 (Urban Railway)
- [ ] Ensure parent stations do not have routes linked to
```

```[tasklist]
### Tasks (data clean-up & fixes)
- [ ] Produce parent_station for all stops (use stop_id prefix for DELFI data)
- [ ] Ensure pre-existing parent_stations never have any trips associated with them (if so, create duplicate parent_station and re-assign location_type of old parent station to 0)
- [ ] Fix invalid lat/long of stops with the help of other stops with the same parent station or name
```
