### ISSUE TITLE
Docs v2

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2780]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2781
- [ ] https://github.com/goat-community/goat/issues/2782
- [ ] https://github.com/goat-community/goat/issues/2783
- [ ] https://github.com/goat-community/goat/issues/2784
- [ ] https://github.com/goat-community/goat/issues/2785
- [ ] https://github.com/goat-community/goat/issues/2786
- [ ] https://github.com/goat-community/goat/issues/2787
- [ ] https://github.com/goat-community/goat/issues/2788
- [ ] https://github.com/goat-community/goat/issues/2789
- [ ] https://github.com/goat-community/goat/issues/2790
- [ ] https://github.com/goat-community/goat/issues/2791
- [ ] https://github.com/goat-community/goat/issues/2792
- [ ] https://github.com/goat-community/goat/issues/2793
- [ ] https://github.com/goat-community/goat/issues/2794
- [ ] https://github.com/goat-community/goat/issues/2795
- [ ] https://github.com/goat-community/goat/issues/2797
- [ ] https://github.com/goat-community/goat/issues/2811
- [ ] https://github.com/goat-community/goat/issues/2796
- [ ] https://github.com/goat-community/goat/issues/2814
- [ ] https://github.com/goat-community/goat/issues/2815
- [ ] https://github.com/goat-community/goat/issues/2817
- [ ] https://github.com/goat-community/goat/issues/2798
- [ ] https://github.com/goat-community/goat/issues/2812
- [ ] https://github.com/goat-community/goat/issues/2800
- [ ] https://github.com/goat-community/goat/issues/2819
- [ ] https://github.com/goat-community/goat/issues/2818
- [ ] https://github.com/goat-community/goat/issues/2804
- [ ] https://github.com/goat-community/goat/issues/2801
- [ ] https://github.com/goat-community/goat/issues/2802
- [ ] https://github.com/goat-community/goat/issues/2803
- [ ] https://github.com/goat-community/goat/issues/2820
- [ ] https://github.com/goat-community/goat/issues/2845
- [ ] https://github.com/goat-community/goat/issues/2834
- [ ] https://github.com/goat-community/goat/issues/2850
- [ ] https://github.com/goat-community/goat/issues/2852
- [ ] https://github.com/goat-community/goat/issues/2853
- [ ] https://github.com/goat-community/goat/issues/2851
- [ ] https://github.com/goat-community/goat/issues/2876
- [ ] https://github.com/goat-community/goat/issues/2889
- [ ] https://github.com/goat-community/goat/issues/2890
- [ ] https://github.com/goat-community/goat/issues/2891
- [x] https://github.com/goat-community/goat/issues/2893
- [ ] https://github.com/goat-community/goat/issues/2894
- [ ] https://github.com/goat-community/goat/issues/3051
- [ ] https://github.com/goat-community/goat/issues/3053
- [ ] https://github.com/goat-community/goat/issues/3058
- [ ] https://github.com/goat-community/goat/issues/3122
- [ ] https://github.com/goat-community/goat/issues/3123
- [ ] https://github.com/goat-community/goat/issues/3202
- [ ] https://github.com/goat-community/goat/issues/3204
- [ ] https://github.com/goat-community/goat/issues/3207
- [ ] https://github.com/goat-community/goat/issues/3224
- [ ] https://github.com/goat-community/goat/issues/3242
- [ ] https://github.com/goat-community/goat/issues/3287
```
