### ISSUE TITLE
Docs: Data Catalog

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2782]
```[tasklist]
### Tasks
- [x] Draft (Irem)
- [x] Check (Elias & Ulrike)
- [x] Adjustments (Ana)
- [ ] Final Check (Elias & Nihar)
```

**Comment by iremkapucuoglu** [comment]
TODOs after the implementation is done:

- Update overview image
- Show that the datasets can be used in GOAT
- Show how dataset filter works

**Comment by AnaSasso** [comment]
- [ ] Update overview image 
> Added data explorer image
- [ ] Show that the datasets can be used in GOAT
> step by step add dataset as a layer
- [ ] Show how dataset filter works
>hint to filter data

**Comment by nihar1024** [comment]
Thanks for updating this. A few comments:


![Image](https://github.com/goat-community/goat/assets/24190384/6aeba976-9a2b-4e06-b528-9baca80a9ff9)

It would be better to use a screenshot showing the entire page and then highlight the Catalog menu item. This screenshot would be hard for users to understand without context.

**Comment by nihar1024** [comment]
![Image](https://github.com/goat-community/goat/assets/24190384/d5c3df21-806b-4912-9b5e-c5153e79c80c)

Same here, a full size screenshot would be better. Also, a larger image size as shown in the docs page would be nice.

**Comment by nihar1024** [comment]
![Image](https://github.com/goat-community/goat/assets/24190384/48996c14-da7f-4bf5-a0cc-3bd286cb364b)

This hyperlink points to the wrong "Filters" page as that refers to filtering user datasets. This should instead point to the `../map/filter` page. Could we add this as the last step of the usage guide rather than a note? As we would want users to always filter the data.

**Comment by nihar1024** [comment]
Lastly, I think the page might be easier to understand if the "Explore the GOAT data catalog" section is at the top and the "Use catalog data in your GOAT project" section is below it. Could we swap the ordering of the two?



![Image](https://github.com/goat-community/goat/assets/24190384/4d7f7197-8ce6-4295-8dbf-adaf027fdf68)

**Comment by AnaSasso** [comment]
> ![Image](https://private-user-images.githubusercontent.com/24190384/332664598-48996c14-da7f-4bf5-a0cc-3bd286cb364b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTc4MTEsIm5iZiI6MTcxNjQxNzUxMSwicGF0aCI6Ii8yNDE5MDM4NC8zMzI2NjQ1OTgtNDg5OTZjMTQtZGE3Zi00YmY1LWEwY2MtM2JkMjg2Y2IzNjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIyMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYmFiZDE0YzczMTMxYjJjNjE4MDc5YmU3YmE0ZmMwOWM5YWE1MzY4NTYwMzZiODhkM2FmZDY3YjEyOGViY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ygQaP9v10atfF_IORoZFu5I2cNDZvXFkDlWzmVoiqEQ)
> 
> This hyperlink points to the wrong "Filters" page as that refers to filtering user datasets. This should instead point to the `../map/filter` page.
> 
> Also, could we add this as the last step of the usage guide rather than a note? As we would want users to always filter the data.

I couldnt add a url to the stepper, so I added a 4th step but kept the hint
