### ISSUE TITLE
Docs: Accessibility Indicators - Catchments

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2800]
```[tasklist]
### Tasks
- [x] Prepare Structure of page (Ulrike)
- [x] Step-by-Step-Guide Draft (Irem)
- [x] Step-by-Step-Guide Check (Ulrike)
- [x] Step-by-Step-Guide Adjustments (Irem)
- [x] Final Check & Additions (Elias & Ulrike)
```

**Comment by EPajares** [comment]
Here are the schemas:

https://github.com/goat-community/goat-core/blob/main/src/schemas/motorized_mobility.py
https://github.com/goat-community/goat-core/blob/main/src/schemas/active_mobility.py

The are called IIsochroneActiveMobility AND IIsochroneMotorizedMobility. You can study them and the inherit a lot of dependencies.

**Comment by UJehle** [comment]
Needs to be finalized when the implementation is done (snyc. with dev-team). Draft-File is saved in OneDrive.

**Comment by nihar1024** [comment]
TODO:

- [ ] Update car
