### ISSUE TITLE
Docs: Accessibility Indicators - ÖV Güteklassen

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2801]
```[tasklist]
### Tasks
- [x] Explanation (Ulrike)
- [x] Step-by-step guideline (Irem)
- [x] Update Screenshot in "Visualization" section (Irem)
- [x] Check step-by-step guideline (Ulrike)
```

**Comment by EPajares** [comment]
Here is the one for ÖV Güteklassen; https://github.com/goat-community/goat-core/blob/main/src/schemas/motorized_mobility.py

**Comment by nihar1024** [comment]
TODO: Add geofence

**Comment by AnaSasso** [comment]
done
