### ISSUE TITLE
Docs: Accessibility Indicators - Heatmap Connectivity

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2819]
```[tasklist]
### Tasks
- [ ] Update Step-by-step guideline (Irem)
- [ ] Update Screenshots (Irem)
- [ ] Check updated Step-by-Step guideline (Ulrike)
- [ ] Check Technical details (Elias?)
```
