### ISSUE TITLE
Further optimizations to goat-routing active mobility endpoint

### ISSUE THREAD

**Issue by nihar1024** [goat-community/goat#2859]
```[tasklist]
### Tasks
- [ ] Use combination of H3_6 ring and ST_Intersects to identify relevant cells optimally
- [ ] Explore if higher resolution cells could improve performance by reducing amount of data to load
- [ ] Standardize segment lengths in data_preparation (even if a segment does not cross cell borders)
- [ ] Explore if using a local DB instance for computing artifical segments would be faster
- [ ] Do starting points need to be written to the DB again?
- [ ] Possible to further speed up conversion of Polars DF > dict of Numpy arrays?
- [ ] Combine and refactor crud_isochrone async & sync versions (sync version used for heatmap matrix computation)
- [ ] Consider removing artifical segments (from origin to street network) for bicycle and car routing
```
