### ISSUE TITLE
Beta release bugs

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2879]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/2880
- [ ] https://github.com/goat-community/goat/issues/2881
- [ ] https://github.com/goat-community/goat/issues/2882
- [ ] https://github.com/goat-community/goat/issues/2883
- [ ] https://github.com/goat-community/goat/issues/2884
- [ ] https://github.com/goat-community/goat/issues/2885
- [ ] https://github.com/goat-community/goat/issues/2895
- [ ] https://github.com/goat-community/goat/issues/2896
- [ ] https://github.com/goat-community/goat/issues/2897
- [ ] https://github.com/goat-community/goat/issues/2898
- [ ] https://github.com/goat-community/goat/issues/2899
- [ ] https://github.com/goat-community/goat/issues/2892
- [ ] https://github.com/goat-community/goat/issues/2900
- [ ] https://github.com/goat-community/goat/issues/2901
- [ ] https://github.com/goat-community/goat/issues/2902
- [ ] https://github.com/goat-community/goat/issues/2903
- [ ] https://github.com/goat-community/goat/issues/2904
- [ ] https://github.com/goat-community/goat/issues/2905
- [ ] https://github.com/goat-community/goat/issues/2906
- [ ] https://github.com/goat-community/goat/issues/2907
- [ ] https://github.com/goat-community/goat/issues/2913
- [ ] https://github.com/goat-community/goat/issues/2936
- [ ] https://github.com/goat-community/goat/issues/2937
- [ ] https://github.com/goat-community/goat/issues/2938
- [ ] https://github.com/goat-community/goat/issues/2940
- [ ] https://github.com/goat-community/goat/issues/2941
- [ ] https://github.com/goat-community/goat/issues/2943
- [ ] https://github.com/goat-community/goat/issues/2948
- [ ] https://github.com/goat-community/goat/issues/2949
- [ ] https://github.com/goat-community/goat/issues/2951
- [ ] https://github.com/goat-community/goat/issues/2950
- [ ] https://github.com/goat-community/goat/issues/2965
- [ ] https://github.com/goat-community/goat/issues/2967
- [ ] https://github.com/goat-community/goat/issues/2968
- [ ] https://github.com/goat-community/goat/issues/2969
- [ ] https://github.com/goat-community/goat/issues/2970
- [ ] https://github.com/goat-community/goat/issues/2972
- [ ] https://github.com/goat-community/goat/issues/2973
- [ ] https://github.com/goat-community/goat/issues/2974
- [ ] https://github.com/goat-community/goat/issues/2975
- [ ] https://github.com/goat-community/goat/issues/2976
- [ ] https://github.com/goat-community/goat/issues/2977
- [ ] https://github.com/goat-community/goat/issues/2995
- [ ] https://github.com/goat-community/goat/issues/2979
- [ ] https://github.com/goat-community/goat/issues/2985
- [ ] https://github.com/goat-community/goat/issues/2986
- [ ] https://github.com/goat-community/goat/issues/2987
- [ ] https://github.com/goat-community/goat/issues/2988
- [ ] https://github.com/goat-community/goat/issues/2989
- [ ] https://github.com/goat-community/goat/issues/2991
- [ ] https://github.com/goat-community/goat/issues/2994
- [ ] https://github.com/goat-community/goat/issues/2998
- [ ] https://github.com/goat-community/goat/issues/3004
- [ ] https://github.com/goat-community/goat/issues/3028
- [ ] https://github.com/goat-community/goat/issues/3005
- [ ] https://github.com/goat-community/goat/issues/3006
- [ ] https://github.com/goat-community/goat/issues/3029
- [ ] https://github.com/goat-community/goat/issues/3007
- [ ] https://github.com/goat-community/goat/issues/3012
- [ ] https://github.com/goat-community/goat/issues/3013
- [ ] https://github.com/goat-community/goat/issues/3016
- [ ] https://github.com/goat-community/goat/issues/3018
- [ ] https://github.com/goat-community/goat/issues/3017
- [ ] https://github.com/goat-community/goat/issues/3022
- [ ] https://github.com/goat-community/goat/issues/3023
- [ ] https://github.com/goat-community/goat/issues/3025
- [ ] https://github.com/goat-community/goat/issues/3027
- [ ] https://github.com/goat-community/goat/issues/3033
- [ ] https://github.com/goat-community/goat/issues/3031
- [ ] https://github.com/goat-community/goat/issues/3032
- [ ] https://github.com/goat-community/goat/issues/3034
- [ ] https://github.com/goat-community/goat/issues/3035
- [ ] https://github.com/goat-community/goat/issues/3036
- [ ] https://github.com/goat-community/goat/issues/3037
- [ ] https://github.com/goat-community/goat/issues/3038
- [ ] https://github.com/goat-community/goat/issues/3039
- [ ] https://github.com/goat-community/goat/issues/3040
- [ ] https://github.com/goat-community/goat/issues/3045
- [ ] https://github.com/goat-community/goat/issues/3046
- [ ] https://github.com/goat-community/goat/issues/3055
- [ ] https://github.com/goat-community/goat/issues/3056
- [ ] https://github.com/goat-community/goat/issues/3057
- [ ] https://github.com/goat-community/goat/issues/3061
- [ ] https://github.com/goat-community/goat/issues/3062
- [ ] https://github.com/goat-community/goat/issues/3063
- [ ] https://github.com/goat-community/goat/issues/3064
- [ ] https://github.com/goat-community/goat/issues/3065
- [ ] https://github.com/goat-community/goat/issues/3069
- [ ] https://github.com/goat-community/goat/issues/3085
- [ ] https://github.com/goat-community/goat/issues/3089
- [ ] https://github.com/goat-community/goat/issues/3094
- [ ] https://github.com/goat-community/goat/issues/3116
- [ ] https://github.com/goat-community/goat/issues/3152
- [ ] https://github.com/goat-community/goat/issues/3209
- [ ] https://github.com/goat-community/goat/issues/3210
- [ ] https://github.com/goat-community/goat/issues/3228
- [ ] https://github.com/goat-community/goat/issues/3229
- [ ] https://github.com/goat-community/goat/issues/3241
- [ ] https://github.com/goat-community/goat/issues/3248
- [ ] https://github.com/goat-community/goat/issues/3271
- [ ] https://github.com/goat-community/goat/issues/3272
- [ ] https://github.com/goat-community/goat/issues/3279
- [ ] https://github.com/goat-community/goat/issues/3299
- [ ] https://github.com/goat-community/goat/issues/3303
- [ ] https://github.com/goat-community/goat/issues/3306
- [ ] https://github.com/goat-community/goat/issues/3307
```
