### ISSUE TITLE
data-preparation: Crucial improvements to network_pt collection

### ISSUE THREAD

**Issue by nihar1024** [goat-community/goat#2908]
```[tasklist]
### Tasks
- [x] Filter Europe OSM .pbf to discard non highway entities (output .o5m)
- [x] Use ST_ExteriorRing function to get correct perimeter geometry of sub regions (for .poly file)
- [x] Clip Europe OSM to sub regions (but drop relations, author, etc), convert back to .pbf
```
