### ISSUE TITLE
DOC Bugs

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/goat#3058]
```[tasklist]
### Tasks
- [ ] Sample task
- [ ] https://github.com/goat-community/goat/issues/3059
- [x] Remove correlation page
- [ ] Say "feature will be online soon"
- [ ] https://github.com/goat-community/goat/issues/3198
- [ ] https://github.com/goat-community/goat/issues/3201
- [ ] https://github.com/goat-community/goat/issues/3203
- [ ] https://github.com/goat-community/goat/issues/3205
```
