### ISSUE TITLE
Docs: Video Tutorials

### ISSUE THREAD

**Issue by nihar1024** [goat-community/goat#3122]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/3124
- [ ] https://github.com/goat-community/goat/issues/3125
- [ ] https://github.com/goat-community/goat/issues/3126
- [ ] https://github.com/goat-community/goat/issues/3127
- [ ] https://github.com/goat-community/goat/issues/3128
- [ ] https://github.com/goat-community/goat/issues/3129
- [ ] https://github.com/goat-community/goat/issues/3130
- [ ] https://github.com/goat-community/goat/issues/3131
- [ ] https://github.com/goat-community/goat/issues/3132
- [ ] https://github.com/goat-community/goat/issues/3133
- [ ] https://github.com/goat-community/goat/issues/3134
- [ ] https://github.com/goat-community/goat/issues/3135
- [ ] https://github.com/goat-community/goat/issues/3147
- [ ] https://github.com/goat-community/goat/issues/3199
- [ ] https://github.com/goat-community/goat/issues/3200
- [ ] https://github.com/goat-community/goat/issues/3219
```
