### ISSUE TITLE
Docs: Translation

### ISSUE THREAD

**Issue by nihar1024** [goat-community/goat#3123]
```[tasklist]
### Tasks
- [ ] https://github.com/goat-community/goat/issues/3137
- [ ] https://github.com/goat-community/goat/issues/3157
- [ ] https://github.com/goat-community/goat/issues/3158
- [ ] https://github.com/goat-community/goat/issues/3159
- [ ] https://github.com/goat-community/goat/issues/3160
- [ ] https://github.com/goat-community/goat/issues/3161
- [ ] https://github.com/goat-community/goat/issues/3162
- [ ] https://github.com/goat-community/goat/issues/3163
- [ ] https://github.com/goat-community/goat/issues/3164
- [ ] https://github.com/goat-community/goat/issues/3165
- [ ] https://github.com/goat-community/goat/issues/3166
- [ ] https://github.com/goat-community/goat/issues/3167
- [ ] https://github.com/goat-community/goat/issues/3168
- [ ] https://github.com/goat-community/goat/issues/3169
- [ ] https://github.com/goat-community/goat/issues/3170
- [ ] https://github.com/goat-community/goat/issues/3171
- [ ] https://github.com/goat-community/goat/issues/3172
- [ ] https://github.com/goat-community/goat/issues/3173
- [ ] https://github.com/goat-community/goat/issues/3145
- [ ] https://github.com/goat-community/goat/issues/3136
- [ ] https://github.com/goat-community/goat/issues/3138
- [ ] https://github.com/goat-community/goat/issues/3139
- [ ] https://github.com/goat-community/goat/issues/3140
- [ ] https://github.com/goat-community/goat/issues/3141
- [ ] https://github.com/goat-community/goat/issues/3142
- [ ] https://github.com/goat-community/goat/issues/3143
- [ ] https://github.com/goat-community/goat/issues/3144
- [ ] https://github.com/goat-community/goat/issues/3174
- [ ] https://github.com/goat-community/goat/issues/3175
- [ ] https://github.com/goat-community/goat/issues/3176
- [ ] https://github.com/goat-community/goat/issues/3177
- [ ] https://github.com/goat-community/goat/issues/3178
- [ ] https://github.com/goat-community/goat/issues/3179
- [ ] https://github.com/goat-community/goat/issues/3180
- [ ] https://github.com/goat-community/goat/issues/3181
- [ ] https://github.com/goat-community/goat/issues/3182
- [ ] https://github.com/goat-community/goat/issues/3183
- [ ] https://github.com/goat-community/goat/issues/3184
- [ ] https://github.com/goat-community/goat/issues/3185
- [ ] https://github.com/goat-community/goat/issues/3186
- [ ] https://github.com/goat-community/goat/issues/3187
- [ ] https://github.com/goat-community/goat/issues/3188
- [ ] https://github.com/goat-community/goat/issues/3189
- [ ] https://github.com/goat-community/goat/issues/3190
- [ ] https://github.com/goat-community/goat/issues/3191
- [ ] https://github.com/goat-community/goat/issues/3192
- [ ] https://github.com/goat-community/goat/issues/3193
- [ ] https://github.com/goat-community/goat/issues/3194
- [ ] https://github.com/goat-community/goat/issues/3195
- [ ] https://github.com/goat-community/goat/issues/3196
- [ ] https://github.com/goat-community/goat/issues/3197
- [ ] https://github.com/goat-community/goat/issues/3211
```
